# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 399ef56bbcbcc35332c8d4306363b6e9a9b2dc877e5a5d1a7ab16fd3d35a0cc66e84a793c488ea37d3a57f7cc3b89982375ce3d3528bcf79a28f8fcde68fc021

test:
  secret_key_base: b3f1455f757a6ffd803a716e9a06e8cc179debc86e80904ac2220fb9d9d0441e502ec05acf9d6699f7bfecea8c0770b11ddd66b212f5a5ff94f9f9fe972f82f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
