# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f55ba4ec6470a4a6f4713e528e556e373a2e3a11d33cf9cb2d2fa7ab2bbaedda12ad8aee6e54889e9cd75090bcce3f06eb8cfd73ded32537b7eef9c97432edc4

test:
  secret_key_base: a1d5a17646893948d05f68bcbe2d0e6bbe6b8b07405e98f284893b10d2ac3ff3535f33f2a361eda199b14735e5b4975c8af207e8c9e8ca89d570d9be1758a11a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
